version: '3.9'

services:
  kurobase:
    image: ken-kuro/kurobase:latest
    container_name: kurobase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@kurobase-pg:5432/kurobase?connection_limit=15&pool_timeout=0
      DB_REDIS_URL: redis://redis:6379
    env_file:
      - .env
    depends_on:
      - kurobase-pg
      - redis
    volumes:
      - .uploads:/app/uploads

  kurobase-pg:
    image: ankane/pgvector:latest
    container_name: kurobase-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kurobase
    volumes:
      - .postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - .redis:/data
